webskeleton/src/main/java/id/web/faisalabdillah/domain/Role.java
/**
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *	 
 */

package id.web.faisalabdillah.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="MST_ROLE")
public class Role extends BaseDomain {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private String code;
	@Column
	private String description;

	

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}

webskeleton/src/main/java/id/web/faisalabdillah/common/CommonResultBean.java
/**
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *	 
 */

package id.web.faisalabdillah.common;

public class CommonResultBean<T> implements IResultBean<T>{
	private int size;
	private int currentPage;
	private int pageSize;
	private T result;
	private Object message;
	private boolean success;
	
	public int getNextPage(){
		return currentPage>=getMaxPage()?currentPage:currentPage+1;
	}
	public int getPrevPage(){
		return currentPage<=1?currentPage:currentPage-1;
	}
	
	public int getIndex(int page){
		int index=(page-1)*pageSize;
		return index;
	}
	
	public static int getIndex(int page,int pageSize){
		int index=(page-1)*pageSize;
		return index;
	}
	public int getCurrentIndex(){
		return getIndex(currentPage);
	}
	public int getMaxPage(){
		int max=size/pageSize;
		if(size%pageSize!=0){
			max++;
		}
		return max;
	}
	public int getSize() {
		return size;
	}
	public void setSize(int size) {
		this.size = size;
	}
	public int getCurrentPage() {
		return currentPage;
	}
	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}
	public int getPageSize() {
		return pageSize;
	}
	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}
	
	public Object getMessage() {
		return message;
	}
	public void setMessage(Object message) {
		this.message = message;
	}
	public boolean isSuccess() {
		return success;
	}
	public void setSuccess(boolean success) {
		this.success = success;
	}
	/* (non-Javadoc)
	 * @see id.web.faisalabdillah.common.IResultBean#getResult()
	 */
	@Override
	public T getResult() {
		return result;
	}
	/* (non-Javadoc)
	 * @see id.web.faisalabdillah.common.IResultBean#setResult(java.lang.Object)
	 */
	@Override
	public void setResult(T t) {
		this.result = t;
	}
	
	
}

webskeleton/src/main/webapp/WEB-INF/pages/admin/role/add-role.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Role Administrator</title>
</head>
<body>
<div class="row-fluid">
	<div class="span3">
	<div class="well sidebar-nav">
				<ul class="nav nav-list">
					<li class="nav-header">Role Admin</li>
					<li class="active"><a href="<%=request.getContextPath()%>/admin/role/add">Add</a></li>
				</ul>
			</div>
	</div>
	<div class="span9">
	<c:if test="${not empty cf}">
	<div class="alert ${cf.success?'alert-success':'alert-error' }">
		${cf.message }
	</div>
	</c:if>
	<form:form commandName="roleCommand" cssClass="well" method="post">
		<h2>Role Form</h2>
		<form:label path="code">Code</form:label>
		<form:input path="code"/>
		<form:label path="description">Description</form:label>
		<form:textarea path="description"/>
		<br/>
		<div class="btn-group">
		<button type="submit" class="btn btn-primary">Add</button>
		<button type="reset" class="btn btn-primary">Reset</button>
		</div>
	</form:form>
	<a name="table"></a>
	<table class="table table-striped">
		<thead>
			<tr><th colspan="4"><form method="get" class="well form-search"><input type="text" name="q" class="search-query"/><button type="submit" name="search" class="btn">Search</button> </form></th></tr>
			<tr><th>No</th><th>Code</th><th>Description</th></tr>
		</thead>
		<tbody>
			<c:forEach items="${roles.result}" var="role" varStatus="i">
			<tr><td>${i.count}</td><td>${role.code }</td><td>${role.description}</td><td><div class="btn-group"><a class="btn" href="<%=request.getContextPath()+"/admin/role/del" %>/${role.code}">Delete</a><a class="btn" href="#">Edit</a></div></td></tr>
			</c:forEach>
			<c:if test="${resultSize == 0 }">
			<tr><td colspan="4">0 Result</td></tr>
			</c:if>
		</tbody>
		<tfoot>
			<tr><td colspan="4">
				<div class="pagination">
					<ul>
						<li class="${roles.prevPage == roles.currentPage?'disabled':'' }" >
						<c:choose>
						<c:when test="${roles.prevPage!=roles.currentPage }">
							<a href="<%=request.getContextPath()+"/admin/role/add" %>/${roles.pageSize}/${roles.prevPage}#table?q=${q}">prev</a>
							</c:when>
							<c:otherwise>
								<a>prev</a>
							</c:otherwise>
						</c:choose>
						</li>
						<c:forEach begin="1" end="${roles.maxPage}" var="i">
						<li class="${i == roles.currentPage?'active':'' }"><a href="<%=request.getContextPath()+"/admin/role/add" %>/${roles.pageSize}/${i}#table?q=${q}">${i}</a></li>
						</c:forEach>
						<li class="${roles.nextPage == roles.currentPage?'disabled':'' }">
						<c:choose>
							<c:when test="${roles.nextPage!=roles.currentPage }">
							<a href="<%=request.getContextPath()+"/admin/role/add" %>/${roles.pageSize}/${roles.nextPage}#table?q=${q}">next</a>
							</c:when>
							<c:otherwise>
								<a>next</a>
							</c:otherwise>
						</c:choose></li>
					</ul>
				</div>
			</td></tr>
		</tfoot>
	</table>
	</div>
</div>
${roles.size }
</body>
</html>